name: Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin' # Or your preferred JDK distribution

    - name: fix permissions
      run: chmod +x mvnw

    - name: Build with Maven
      run: ./mvnw clean install

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest

    - name: Deploy to Oracle VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ORACLE_HOST }}
        username: ${{ secrets.ORACLE_USERNAME }}
        key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker stop my_app || true
          docker rm my_app || true
          docker run -d -p 443:8443 \
            -v ${{ vars.KEYSTORE_DIR }}/keystore.p12:/app/keystore.p12 \
            -e SPRING_PROFILES_ACTIVE=deploy,low-memory,tls \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --name my_app ${{ secrets.DOCKER_USERNAME }}/my-app:latest
